//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Checkbox.Wcf.Services.Proxies
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceOperationResultOfResponseSummaryDataVUqw3SxC", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    public partial class ServiceOperationResultOfResponseSummaryDataVUqw3SxC : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool CallSuccessField;
        
        private string FailureExceptionTypeField;
        
        private string FailureMessageField;
        
        private Checkbox.Wcf.Services.Proxies.ResponseSummaryData ResultDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CallSuccess
        {
            get
            {
                return this.CallSuccessField;
            }
            set
            {
                this.CallSuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailureExceptionType
        {
            get
            {
                return this.FailureExceptionTypeField;
            }
            set
            {
                this.FailureExceptionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailureMessage
        {
            get
            {
                return this.FailureMessageField;
            }
            set
            {
                this.FailureMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Checkbox.Wcf.Services.Proxies.ResponseSummaryData ResultData
        {
            get
            {
                return this.ResultDataField;
            }
            set
            {
                this.ResultDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseSummaryData", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    public partial class ResponseSummaryData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CompletedResponseCountField;
        
        private int IncompleteResponseCountField;
        
        private int SurveyIdField;
        
        private int TestResponseCountField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompletedResponseCount
        {
            get
            {
                return this.CompletedResponseCountField;
            }
            set
            {
                this.CompletedResponseCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IncompleteResponseCount
        {
            get
            {
                return this.IncompleteResponseCountField;
            }
            set
            {
                this.IncompleteResponseCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SurveyId
        {
            get
            {
                return this.SurveyIdField;
            }
            set
            {
                this.SurveyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TestResponseCount
        {
            get
            {
                return this.TestResponseCountField;
            }
            set
            {
                this.TestResponseCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceOperationResultOfArrayOfResponseDataVUqw3SxC", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    public partial class ServiceOperationResultOfArrayOfResponseDataVUqw3SxC : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool CallSuccessField;
        
        private string FailureExceptionTypeField;
        
        private string FailureMessageField;
        
        private Checkbox.Wcf.Services.Proxies.ResponseData[] ResultDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CallSuccess
        {
            get
            {
                return this.CallSuccessField;
            }
            set
            {
                this.CallSuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailureExceptionType
        {
            get
            {
                return this.FailureExceptionTypeField;
            }
            set
            {
                this.FailureExceptionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailureMessage
        {
            get
            {
                return this.FailureMessageField;
            }
            set
            {
                this.FailureMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Checkbox.Wcf.Services.Proxies.ResponseData[] ResultData
        {
            get
            {
                return this.ResultDataField;
            }
            set
            {
                this.ResultDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseData", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    public partial class ResponseData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<System.Guid> AnonymousRespondentGuidField;
        
        private Checkbox.Wcf.Services.Proxies.ResponseItemAnswerData[] AnswersField;
        
        private System.Nullable<System.DateTime> CompletionDateField;
        
        private System.Guid GuidField;
        
        private long IdField;
        
        private string InviteeField;
        
        private bool IsAnonymizedField;
        
        private bool IsTestField;
        
        private System.Nullable<System.DateTime> LastEditDateField;
        
        private int LastPageViewedField;
        
        private string NetworkUserField;
        
        private string RespondentIpField;
        
        private string ResponseLanguageField;
        
        private System.Nullable<System.DateTime> StartedField;
        
        private string SurveyNameField;
        
        private string UserIdentifierField;
        
        private System.Nullable<System.Guid> WorkflowSessionIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> AnonymousRespondentGuid
        {
            get
            {
                return this.AnonymousRespondentGuidField;
            }
            set
            {
                this.AnonymousRespondentGuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Checkbox.Wcf.Services.Proxies.ResponseItemAnswerData[] Answers
        {
            get
            {
                return this.AnswersField;
            }
            set
            {
                this.AnswersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CompletionDate
        {
            get
            {
                return this.CompletionDateField;
            }
            set
            {
                this.CompletionDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Guid
        {
            get
            {
                return this.GuidField;
            }
            set
            {
                this.GuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Invitee
        {
            get
            {
                return this.InviteeField;
            }
            set
            {
                this.InviteeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAnonymized
        {
            get
            {
                return this.IsAnonymizedField;
            }
            set
            {
                this.IsAnonymizedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTest
        {
            get
            {
                return this.IsTestField;
            }
            set
            {
                this.IsTestField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastEditDate
        {
            get
            {
                return this.LastEditDateField;
            }
            set
            {
                this.LastEditDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LastPageViewed
        {
            get
            {
                return this.LastPageViewedField;
            }
            set
            {
                this.LastPageViewedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NetworkUser
        {
            get
            {
                return this.NetworkUserField;
            }
            set
            {
                this.NetworkUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RespondentIp
        {
            get
            {
                return this.RespondentIpField;
            }
            set
            {
                this.RespondentIpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseLanguage
        {
            get
            {
                return this.ResponseLanguageField;
            }
            set
            {
                this.ResponseLanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Started
        {
            get
            {
                return this.StartedField;
            }
            set
            {
                this.StartedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SurveyName
        {
            get
            {
                return this.SurveyNameField;
            }
            set
            {
                this.SurveyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserIdentifier
        {
            get
            {
                return this.UserIdentifierField;
            }
            set
            {
                this.UserIdentifierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> WorkflowSessionId
        {
            get
            {
                return this.WorkflowSessionIdField;
            }
            set
            {
                this.WorkflowSessionIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseItemAnswerData", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    public partial class ResponseItemAnswerData : Checkbox.Wcf.Services.Proxies.ItemProxyObject
    {
        
        private string AliasField;
        
        private Checkbox.Wcf.Services.Proxies.ResponseItemAnswer[] AnswersField;
        
        private string DescriptionField;
        
        private string TextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Alias
        {
            get
            {
                return this.AliasField;
            }
            set
            {
                this.AliasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Checkbox.Wcf.Services.Proxies.ResponseItemAnswer[] Answers
        {
            get
            {
                return this.AnswersField;
            }
            set
            {
                this.AnswersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemProxyObject", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseItemAnswerData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfResponseSummaryDataVUqw3SxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseSummaryData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfArrayOfResponseDataVUqw3SxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseData[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseItemAnswerData[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValueCollection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValue[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValue))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseItemAnswer[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseItemAnswer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfanyType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfPagedListResultOfArrayOfResponseDataVUqw3SxCVUqw3SxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResultOfArrayOfResponseDataVUqw3SxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfArrayOfGroupedResultOfResponseDataVUqw3SxCVUqw3SxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.GroupedResultOfResponseDataVUqw3SxC[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.GroupedResultOfResponseDataVUqw3SxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfstring))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfResponseAggregatedDataVUqw3SxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseAggregatedData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.AggregateResult[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.AggregateResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ReportResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfArrayOfResponseItemAnswerDataVUqw3SxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfPagedListResultOfResponseExportDataVUqw3SxCVUqw3SxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResultOfResponseExportDataVUqw3SxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseExportData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.UserData[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.UserData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfPagedListResultOfTabularResponseExportDataVUqw3SxCVUqw3SxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResultOfTabularResponseExportDataVUqw3SxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.TabularResponseExportData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValueCollection[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(long[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
    public partial class ItemProxyObject : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private object AdditionalDataField;
        
        private Checkbox.Wcf.Services.Proxies.SimpleNameValueCollection AppearanceDataField;
        
        private Checkbox.Wcf.Services.Proxies.SimpleNameValueCollection InstanceDataField;
        
        private int ItemIdField;
        
        private Checkbox.Wcf.Services.Proxies.SimpleNameValueCollection MetadataField;
        
        private int ParentTemplateIdField;
        
        private string TypeNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object AdditionalData
        {
            get
            {
                return this.AdditionalDataField;
            }
            set
            {
                this.AdditionalDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Checkbox.Wcf.Services.Proxies.SimpleNameValueCollection AppearanceData
        {
            get
            {
                return this.AppearanceDataField;
            }
            set
            {
                this.AppearanceDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Checkbox.Wcf.Services.Proxies.SimpleNameValueCollection InstanceData
        {
            get
            {
                return this.InstanceDataField;
            }
            set
            {
                this.InstanceDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemId
        {
            get
            {
                return this.ItemIdField;
            }
            set
            {
                this.ItemIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Checkbox.Wcf.Services.Proxies.SimpleNameValueCollection Metadata
        {
            get
            {
                return this.MetadataField;
            }
            set
            {
                this.MetadataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentTemplateId
        {
            get
            {
                return this.ParentTemplateIdField;
            }
            set
            {
                this.ParentTemplateIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeName
        {
            get
            {
                return this.TypeNameField;
            }
            set
            {
                this.TypeNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SimpleNameValueCollection", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    public partial class SimpleNameValueCollection : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Checkbox.Wcf.Services.Proxies.SimpleNameValue[] NameValueListField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Checkbox.Wcf.Services.Proxies.SimpleNameValue[] NameValueList
        {
            get
            {
                return this.NameValueListField;
            }
            set
            {
                this.NameValueListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SimpleNameValue", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    public partial class SimpleNameValue : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string NameField;
        
        private string ValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseItemAnswer", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    public partial class ResponseItemAnswer : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AliasField;
        
        private long AnswerIdField;
        
        private string AnswerTextField;
        
        private System.Nullable<int> OptionIdField;
        
        private string OptionTextField;
        
        private System.Nullable<double> PointsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Alias
        {
            get
            {
                return this.AliasField;
            }
            set
            {
                this.AliasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AnswerId
        {
            get
            {
                return this.AnswerIdField;
            }
            set
            {
                this.AnswerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnswerText
        {
            get
            {
                return this.AnswerTextField;
            }
            set
            {
                this.AnswerTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OptionId
        {
            get
            {
                return this.OptionIdField;
            }
            set
            {
                this.OptionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OptionText
        {
            get
            {
                return this.OptionTextField;
            }
            set
            {
                this.OptionTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Points
        {
            get
            {
                return this.PointsField;
            }
            set
            {
                this.PointsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceOperationResultOfanyType", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfResponseSummaryDataVUqw3SxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseSummaryData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfArrayOfResponseDataVUqw3SxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseData[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseItemAnswerData[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseItemAnswerData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ItemProxyObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValueCollection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValue[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValue))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseItemAnswer[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseItemAnswer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfPagedListResultOfArrayOfResponseDataVUqw3SxCVUqw3SxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResultOfArrayOfResponseDataVUqw3SxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfArrayOfGroupedResultOfResponseDataVUqw3SxCVUqw3SxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.GroupedResultOfResponseDataVUqw3SxC[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.GroupedResultOfResponseDataVUqw3SxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfstring))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfResponseAggregatedDataVUqw3SxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseAggregatedData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.AggregateResult[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.AggregateResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ReportResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfArrayOfResponseItemAnswerDataVUqw3SxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfPagedListResultOfResponseExportDataVUqw3SxCVUqw3SxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResultOfResponseExportDataVUqw3SxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ResponseExportData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.UserData[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.UserData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfPagedListResultOfTabularResponseExportDataVUqw3SxCVUqw3SxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PagedListResultOfTabularResponseExportDataVUqw3SxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.TabularResponseExportData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValueCollection[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(long[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
    public partial class ServiceOperationResultOfanyType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool CallSuccessField;
        
        private string FailureExceptionTypeField;
        
        private string FailureMessageField;
        
        private object ResultDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CallSuccess
        {
            get
            {
                return this.CallSuccessField;
            }
            set
            {
                this.CallSuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailureExceptionType
        {
            get
            {
                return this.FailureExceptionTypeField;
            }
            set
            {
                this.FailureExceptionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailureMessage
        {
            get
            {
                return this.FailureMessageField;
            }
            set
            {
                this.FailureMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object ResultData
        {
            get
            {
                return this.ResultDataField;
            }
            set
            {
                this.ResultDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceOperationResultOfPagedListResultOfArrayOfResponseDataVUqw3SxCVUqw3SxC", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    public partial class ServiceOperationResultOfPagedListResultOfArrayOfResponseDataVUqw3SxCVUqw3SxC : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool CallSuccessField;
        
        private string FailureExceptionTypeField;
        
        private string FailureMessageField;
        
        private Checkbox.Wcf.Services.Proxies.PagedListResultOfArrayOfResponseDataVUqw3SxC ResultDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CallSuccess
        {
            get
            {
                return this.CallSuccessField;
            }
            set
            {
                this.CallSuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailureExceptionType
        {
            get
            {
                return this.FailureExceptionTypeField;
            }
            set
            {
                this.FailureExceptionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailureMessage
        {
            get
            {
                return this.FailureMessageField;
            }
            set
            {
                this.FailureMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Checkbox.Wcf.Services.Proxies.PagedListResultOfArrayOfResponseDataVUqw3SxC ResultData
        {
            get
            {
                return this.ResultDataField;
            }
            set
            {
                this.ResultDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagedListResultOfArrayOfResponseDataVUqw3SxC", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    public partial class PagedListResultOfArrayOfResponseDataVUqw3SxC : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Checkbox.Wcf.Services.Proxies.ResponseData[] ResultPageField;
        
        private int TotalItemCountField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Checkbox.Wcf.Services.Proxies.ResponseData[] ResultPage
        {
            get
            {
                return this.ResultPageField;
            }
            set
            {
                this.ResultPageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalItemCount
        {
            get
            {
                return this.TotalItemCountField;
            }
            set
            {
                this.TotalItemCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceOperationResultOfArrayOfGroupedResultOfResponseDataVUqw3SxCVUqw3SxC", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    public partial class ServiceOperationResultOfArrayOfGroupedResultOfResponseDataVUqw3SxCVUqw3SxC : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool CallSuccessField;
        
        private string FailureExceptionTypeField;
        
        private string FailureMessageField;
        
        private Checkbox.Wcf.Services.Proxies.GroupedResultOfResponseDataVUqw3SxC[] ResultDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CallSuccess
        {
            get
            {
                return this.CallSuccessField;
            }
            set
            {
                this.CallSuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailureExceptionType
        {
            get
            {
                return this.FailureExceptionTypeField;
            }
            set
            {
                this.FailureExceptionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailureMessage
        {
            get
            {
                return this.FailureMessageField;
            }
            set
            {
                this.FailureMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Checkbox.Wcf.Services.Proxies.GroupedResultOfResponseDataVUqw3SxC[] ResultData
        {
            get
            {
                return this.ResultDataField;
            }
            set
            {
                this.ResultDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GroupedResultOfResponseDataVUqw3SxC", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    public partial class GroupedResultOfResponseDataVUqw3SxC : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string GroupFieldField;
        
        private string GroupKeyField;
        
        private Checkbox.Wcf.Services.Proxies.ResponseData[] GroupResultsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupField
        {
            get
            {
                return this.GroupFieldField;
            }
            set
            {
                this.GroupFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupKey
        {
            get
            {
                return this.GroupKeyField;
            }
            set
            {
                this.GroupKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Checkbox.Wcf.Services.Proxies.ResponseData[] GroupResults
        {
            get
            {
                return this.GroupResultsField;
            }
            set
            {
                this.GroupResultsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceOperationResultOfstring", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    public partial class ServiceOperationResultOfstring : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool CallSuccessField;
        
        private string FailureExceptionTypeField;
        
        private string FailureMessageField;
        
        private string ResultDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CallSuccess
        {
            get
            {
                return this.CallSuccessField;
            }
            set
            {
                this.CallSuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailureExceptionType
        {
            get
            {
                return this.FailureExceptionTypeField;
            }
            set
            {
                this.FailureExceptionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailureMessage
        {
            get
            {
                return this.FailureMessageField;
            }
            set
            {
                this.FailureMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultData
        {
            get
            {
                return this.ResultDataField;
            }
            set
            {
                this.ResultDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceOperationResultOfResponseAggregatedDataVUqw3SxC", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    public partial class ServiceOperationResultOfResponseAggregatedDataVUqw3SxC : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool CallSuccessField;
        
        private string FailureExceptionTypeField;
        
        private string FailureMessageField;
        
        private Checkbox.Wcf.Services.Proxies.ResponseAggregatedData ResultDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CallSuccess
        {
            get
            {
                return this.CallSuccessField;
            }
            set
            {
                this.CallSuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailureExceptionType
        {
            get
            {
                return this.FailureExceptionTypeField;
            }
            set
            {
                this.FailureExceptionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailureMessage
        {
            get
            {
                return this.FailureMessageField;
            }
            set
            {
                this.FailureMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Checkbox.Wcf.Services.Proxies.ResponseAggregatedData ResultData
        {
            get
            {
                return this.ResultDataField;
            }
            set
            {
                this.ResultDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseAggregatedData", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    public partial class ResponseAggregatedData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Checkbox.Wcf.Services.Proxies.AggregateResult[] AggregateResultsField;
        
        private int CompletedResponseCountField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Checkbox.Wcf.Services.Proxies.AggregateResult[] AggregateResults
        {
            get
            {
                return this.AggregateResultsField;
            }
            set
            {
                this.AggregateResultsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompletedResponseCount
        {
            get
            {
                return this.CompletedResponseCountField;
            }
            set
            {
                this.CompletedResponseCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AggregateResult", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    public partial class AggregateResult : Checkbox.Wcf.Services.Proxies.ReportResult
    {
        
        private int AnswerCountField;
        
        private double AnswerPercentField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AnswerCount
        {
            get
            {
                return this.AnswerCountField;
            }
            set
            {
                this.AnswerCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double AnswerPercent
        {
            get
            {
                return this.AnswerPercentField;
            }
            set
            {
                this.AnswerPercentField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportResult", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.AggregateResult))]
    public partial class ReportResult : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double PointsField;
        
        private int ResultIndexField;
        
        private string ResultKeyField;
        
        private string ResultTextField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Points
        {
            get
            {
                return this.PointsField;
            }
            set
            {
                this.PointsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResultIndex
        {
            get
            {
                return this.ResultIndexField;
            }
            set
            {
                this.ResultIndexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultKey
        {
            get
            {
                return this.ResultKeyField;
            }
            set
            {
                this.ResultKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultText
        {
            get
            {
                return this.ResultTextField;
            }
            set
            {
                this.ResultTextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceOperationResultOfArrayOfResponseItemAnswerDataVUqw3SxC", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    public partial class ServiceOperationResultOfArrayOfResponseItemAnswerDataVUqw3SxC : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool CallSuccessField;
        
        private string FailureExceptionTypeField;
        
        private string FailureMessageField;
        
        private Checkbox.Wcf.Services.Proxies.ResponseItemAnswerData[] ResultDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CallSuccess
        {
            get
            {
                return this.CallSuccessField;
            }
            set
            {
                this.CallSuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailureExceptionType
        {
            get
            {
                return this.FailureExceptionTypeField;
            }
            set
            {
                this.FailureExceptionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailureMessage
        {
            get
            {
                return this.FailureMessageField;
            }
            set
            {
                this.FailureMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Checkbox.Wcf.Services.Proxies.ResponseItemAnswerData[] ResultData
        {
            get
            {
                return this.ResultDataField;
            }
            set
            {
                this.ResultDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceOperationResultOfPagedListResultOfResponseExportDataVUqw3SxCVUqw3SxC", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    public partial class ServiceOperationResultOfPagedListResultOfResponseExportDataVUqw3SxCVUqw3SxC : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool CallSuccessField;
        
        private string FailureExceptionTypeField;
        
        private string FailureMessageField;
        
        private Checkbox.Wcf.Services.Proxies.PagedListResultOfResponseExportDataVUqw3SxC ResultDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CallSuccess
        {
            get
            {
                return this.CallSuccessField;
            }
            set
            {
                this.CallSuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailureExceptionType
        {
            get
            {
                return this.FailureExceptionTypeField;
            }
            set
            {
                this.FailureExceptionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailureMessage
        {
            get
            {
                return this.FailureMessageField;
            }
            set
            {
                this.FailureMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Checkbox.Wcf.Services.Proxies.PagedListResultOfResponseExportDataVUqw3SxC ResultData
        {
            get
            {
                return this.ResultDataField;
            }
            set
            {
                this.ResultDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagedListResultOfResponseExportDataVUqw3SxC", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    public partial class PagedListResultOfResponseExportDataVUqw3SxC : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Checkbox.Wcf.Services.Proxies.ResponseExportData ResultPageField;
        
        private int TotalItemCountField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Checkbox.Wcf.Services.Proxies.ResponseExportData ResultPage
        {
            get
            {
                return this.ResultPageField;
            }
            set
            {
                this.ResultPageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalItemCount
        {
            get
            {
                return this.TotalItemCountField;
            }
            set
            {
                this.TotalItemCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseExportData", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    public partial class ResponseExportData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Checkbox.Wcf.Services.Proxies.UserData[] RespondentsField;
        
        private Checkbox.Wcf.Services.Proxies.ResponseData[] ResponsesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Checkbox.Wcf.Services.Proxies.UserData[] Respondents
        {
            get
            {
                return this.RespondentsField;
            }
            set
            {
                this.RespondentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Checkbox.Wcf.Services.Proxies.ResponseData[] Responses
        {
            get
            {
                return this.ResponsesField;
            }
            set
            {
                this.ResponsesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserData", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    public partial class UserData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AuthenticationTypeField;
        
        private string EmailField;
        
        private string EscapedUniqueIdentifierField;
        
        private string[] GroupMembershipsField;
        
        private bool IsInListField;
        
        private bool LockedOutField;
        
        private Checkbox.Wcf.Services.Proxies.SimpleNameValueCollection ProfileField;
        
        private string[] RoleMembershipsField;
        
        private string UniqueIdentifierField;
        
        private System.Guid UserGuidField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthenticationType
        {
            get
            {
                return this.AuthenticationTypeField;
            }
            set
            {
                this.AuthenticationTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EscapedUniqueIdentifier
        {
            get
            {
                return this.EscapedUniqueIdentifierField;
            }
            set
            {
                this.EscapedUniqueIdentifierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] GroupMemberships
        {
            get
            {
                return this.GroupMembershipsField;
            }
            set
            {
                this.GroupMembershipsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsInList
        {
            get
            {
                return this.IsInListField;
            }
            set
            {
                this.IsInListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LockedOut
        {
            get
            {
                return this.LockedOutField;
            }
            set
            {
                this.LockedOutField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Checkbox.Wcf.Services.Proxies.SimpleNameValueCollection Profile
        {
            get
            {
                return this.ProfileField;
            }
            set
            {
                this.ProfileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] RoleMemberships
        {
            get
            {
                return this.RoleMembershipsField;
            }
            set
            {
                this.RoleMembershipsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UniqueIdentifier
        {
            get
            {
                return this.UniqueIdentifierField;
            }
            set
            {
                this.UniqueIdentifierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserGuid
        {
            get
            {
                return this.UserGuidField;
            }
            set
            {
                this.UserGuidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceOperationResultOfPagedListResultOfTabularResponseExportDataVUqw3SxCVUqw3Sx" +
        "C", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    public partial class ServiceOperationResultOfPagedListResultOfTabularResponseExportDataVUqw3SxCVUqw3SxC : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool CallSuccessField;
        
        private string FailureExceptionTypeField;
        
        private string FailureMessageField;
        
        private Checkbox.Wcf.Services.Proxies.PagedListResultOfTabularResponseExportDataVUqw3SxC ResultDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CallSuccess
        {
            get
            {
                return this.CallSuccessField;
            }
            set
            {
                this.CallSuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailureExceptionType
        {
            get
            {
                return this.FailureExceptionTypeField;
            }
            set
            {
                this.FailureExceptionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailureMessage
        {
            get
            {
                return this.FailureMessageField;
            }
            set
            {
                this.FailureMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Checkbox.Wcf.Services.Proxies.PagedListResultOfTabularResponseExportDataVUqw3SxC ResultData
        {
            get
            {
                return this.ResultDataField;
            }
            set
            {
                this.ResultDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagedListResultOfTabularResponseExportDataVUqw3SxC", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    public partial class PagedListResultOfTabularResponseExportDataVUqw3SxC : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Checkbox.Wcf.Services.Proxies.TabularResponseExportData ResultPageField;
        
        private int TotalItemCountField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Checkbox.Wcf.Services.Proxies.TabularResponseExportData ResultPage
        {
            get
            {
                return this.ResultPageField;
            }
            set
            {
                this.ResultPageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalItemCount
        {
            get
            {
                return this.TotalItemCountField;
            }
            set
            {
                this.TotalItemCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TabularResponseExportData", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    public partial class TabularResponseExportData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Checkbox.Wcf.Services.Proxies.UserData[] RespondentsField;
        
        private Checkbox.Wcf.Services.Proxies.SimpleNameValueCollection[] ResponsesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Checkbox.Wcf.Services.Proxies.UserData[] Respondents
        {
            get
            {
                return this.RespondentsField;
            }
            set
            {
                this.RespondentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Checkbox.Wcf.Services.Proxies.SimpleNameValueCollection[] Responses
        {
            get
            {
                return this.ResponsesField;
            }
            set
            {
                this.ResponsesField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IResponseDataService")]
public interface IResponseDataService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResponseDataService/GetSurveyResponseSummary", ReplyAction="http://tempuri.org/IResponseDataService/GetSurveyResponseSummaryResponse")]
    Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfResponseSummaryDataVUqw3SxC GetSurveyResponseSummary(string authTicket, int surveyId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResponseDataService/ListRecentSurveyResponses", ReplyAction="http://tempuri.org/IResponseDataService/ListRecentSurveyResponsesResponse")]
    Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfArrayOfResponseDataVUqw3SxC ListRecentSurveyResponses(string authTicket, int surveyId, int count);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResponseDataService/UpdateResponseAnswer", ReplyAction="http://tempuri.org/IResponseDataService/UpdateResponseAnswerResponse")]
    Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfanyType UpdateResponseAnswer(string authToken, int surveyId, long responseId, long answerId, string answerText, System.Nullable<int> optionID, System.Nullable<System.DateTime> dateCreated);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResponseDataService/ListSurveyResponses", ReplyAction="http://tempuri.org/IResponseDataService/ListSurveyResponsesResponse")]
    Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfPagedListResultOfArrayOfResponseDataVUqw3SxCVUqw3SxC ListSurveyResponses(string authTicket, int surveyId, int pageNumber, int resultsPerPage, string filterField, string filterValue, string sortField, bool sortAscending);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResponseDataService/ListSurveyResponsesByPeriod", ReplyAction="http://tempuri.org/IResponseDataService/ListSurveyResponsesByPeriodResponse")]
    Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfPagedListResultOfArrayOfResponseDataVUqw3SxCVUqw3SxC ListSurveyResponsesByPeriod(string authTicket, int surveyId, int pageNumber, int resultsPerPage, string filterField, string filterValue, string sortField, bool sortAscending, int period, string dateFieldName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResponseDataService/DeleteSurveyResponses", ReplyAction="http://tempuri.org/IResponseDataService/DeleteSurveyResponsesResponse")]
    Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfanyType DeleteSurveyResponses(string authTicket, int surveyId, long[] responseList);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResponseDataService/DeleteAllSurveyResponses", ReplyAction="http://tempuri.org/IResponseDataService/DeleteAllSurveyResponsesResponse")]
    Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfanyType DeleteAllSurveyResponses(string authTicket, int surveyId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResponseDataService/DeleteAllSurveyTestResponses", ReplyAction="http://tempuri.org/IResponseDataService/DeleteAllSurveyTestResponsesResponse")]
    Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfanyType DeleteAllSurveyTestResponses(string authTicket, int surveyId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResponseDataService/Search", ReplyAction="http://tempuri.org/IResponseDataService/SearchResponse")]
    Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfArrayOfGroupedResultOfResponseDataVUqw3SxCVUqw3SxC Search(string authTicket, string searchTerm);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResponseDataService/GetLifecycleResponseDataInMonths", ReplyAction="http://tempuri.org/IResponseDataService/GetLifecycleResponseDataInMonthsResponse")]
    Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfstring GetLifecycleResponseDataInMonths(string authTicket, int surveyId, int numberOfRecentMonths);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResponseDataService/GetLifecycleResponseDataInDays", ReplyAction="http://tempuri.org/IResponseDataService/GetLifecycleResponseDataInDaysResponse")]
    Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfstring GetLifecycleResponseDataInDays(string authTicket, int surveyId, int periodLengthInDays, int numberOfPeriods);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResponseDataService/GetLifecycleAggregatedResponseDataInDays", ReplyAction="http://tempuri.org/IResponseDataService/GetLifecycleAggregatedResponseDataInDaysR" +
        "esponse")]
    Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfResponseAggregatedDataVUqw3SxC GetLifecycleAggregatedResponseDataInDays(string authTicket, int surveyId, int periodLengthInDays, int numberOfPeriods);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResponseDataService/GetAnswersForResponseByGuid", ReplyAction="http://tempuri.org/IResponseDataService/GetAnswersForResponseByGuidResponse")]
    Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfArrayOfResponseItemAnswerDataVUqw3SxC GetAnswersForResponseByGuid(string authTicket, int surveyId, string languageCode, System.Guid responseGuid);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResponseDataService/ExportResponses", ReplyAction="http://tempuri.org/IResponseDataService/ExportResponsesResponse")]
    Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfPagedListResultOfResponseExportDataVUqw3SxCVUqw3SxC ExportResponses(
                string authToken, 
                int surveyId, 
                int pageNumber, 
                int resultsPerPage, 
                string filterField, 
                string filterValue, 
                string sortField, 
                bool sortAscending, 
                int period, 
                System.DateTime dtStart, 
                System.DateTime dtEnd, 
                bool DetailedResponseInfo, 
                bool DetailedUserInfo, 
                bool IncludeOpenEndedResults, 
                bool IncludeAliases, 
                bool IncludeHiddenItems, 
                bool IncludeIncompleteResponses, 
                bool StripHTMLTagsFromAnswers);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResponseDataService/ExportResponsesTabular", ReplyAction="http://tempuri.org/IResponseDataService/ExportResponsesTabularResponse")]
    Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfPagedListResultOfTabularResponseExportDataVUqw3SxCVUqw3SxC ExportResponsesTabular(
                string authToken, 
                int surveyId, 
                int pageNumber, 
                int resultsPerPage, 
                string filterField, 
                string filterValue, 
                string sortField, 
                bool sortAscending, 
                int period, 
                System.DateTime dtStart, 
                System.DateTime dtEnd, 
                bool DetailedResponseInfo, 
                bool DetailedUserInfo, 
                bool IncludeOpenEndedResults, 
                bool IncludeAliases, 
                bool IncludeHiddenItems, 
                bool IncludeIncompleteResponses, 
                bool StripHTMLTagsFromAnswers, 
                bool StripHTMLTagsFromQuestions, 
                bool MergeAnswersForSelectMany);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IResponseDataServiceChannel : IResponseDataService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ResponseDataServiceClient : System.ServiceModel.ClientBase<IResponseDataService>, IResponseDataService
{
    
    public ResponseDataServiceClient()
    {
    }
    
    public ResponseDataServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ResponseDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ResponseDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ResponseDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfResponseSummaryDataVUqw3SxC GetSurveyResponseSummary(string authTicket, int surveyId)
    {
        return base.Channel.GetSurveyResponseSummary(authTicket, surveyId);
    }
    
    public Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfArrayOfResponseDataVUqw3SxC ListRecentSurveyResponses(string authTicket, int surveyId, int count)
    {
        return base.Channel.ListRecentSurveyResponses(authTicket, surveyId, count);
    }
    
    public Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfanyType UpdateResponseAnswer(string authToken, int surveyId, long responseId, long answerId, string answerText, System.Nullable<int> optionID, System.Nullable<System.DateTime> dateCreated)
    {
        return base.Channel.UpdateResponseAnswer(authToken, surveyId, responseId, answerId, answerText, optionID, dateCreated);
    }
    
    public Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfPagedListResultOfArrayOfResponseDataVUqw3SxCVUqw3SxC ListSurveyResponses(string authTicket, int surveyId, int pageNumber, int resultsPerPage, string filterField, string filterValue, string sortField, bool sortAscending)
    {
        return base.Channel.ListSurveyResponses(authTicket, surveyId, pageNumber, resultsPerPage, filterField, filterValue, sortField, sortAscending);
    }
    
    public Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfPagedListResultOfArrayOfResponseDataVUqw3SxCVUqw3SxC ListSurveyResponsesByPeriod(string authTicket, int surveyId, int pageNumber, int resultsPerPage, string filterField, string filterValue, string sortField, bool sortAscending, int period, string dateFieldName)
    {
        return base.Channel.ListSurveyResponsesByPeriod(authTicket, surveyId, pageNumber, resultsPerPage, filterField, filterValue, sortField, sortAscending, period, dateFieldName);
    }
    
    public Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfanyType DeleteSurveyResponses(string authTicket, int surveyId, long[] responseList)
    {
        return base.Channel.DeleteSurveyResponses(authTicket, surveyId, responseList);
    }
    
    public Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfanyType DeleteAllSurveyResponses(string authTicket, int surveyId)
    {
        return base.Channel.DeleteAllSurveyResponses(authTicket, surveyId);
    }
    
    public Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfanyType DeleteAllSurveyTestResponses(string authTicket, int surveyId)
    {
        return base.Channel.DeleteAllSurveyTestResponses(authTicket, surveyId);
    }
    
    public Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfArrayOfGroupedResultOfResponseDataVUqw3SxCVUqw3SxC Search(string authTicket, string searchTerm)
    {
        return base.Channel.Search(authTicket, searchTerm);
    }
    
    public Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfstring GetLifecycleResponseDataInMonths(string authTicket, int surveyId, int numberOfRecentMonths)
    {
        return base.Channel.GetLifecycleResponseDataInMonths(authTicket, surveyId, numberOfRecentMonths);
    }
    
    public Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfstring GetLifecycleResponseDataInDays(string authTicket, int surveyId, int periodLengthInDays, int numberOfPeriods)
    {
        return base.Channel.GetLifecycleResponseDataInDays(authTicket, surveyId, periodLengthInDays, numberOfPeriods);
    }
    
    public Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfResponseAggregatedDataVUqw3SxC GetLifecycleAggregatedResponseDataInDays(string authTicket, int surveyId, int periodLengthInDays, int numberOfPeriods)
    {
        return base.Channel.GetLifecycleAggregatedResponseDataInDays(authTicket, surveyId, periodLengthInDays, numberOfPeriods);
    }
    
    public Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfArrayOfResponseItemAnswerDataVUqw3SxC GetAnswersForResponseByGuid(string authTicket, int surveyId, string languageCode, System.Guid responseGuid)
    {
        return base.Channel.GetAnswersForResponseByGuid(authTicket, surveyId, languageCode, responseGuid);
    }
    
    public Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfPagedListResultOfResponseExportDataVUqw3SxCVUqw3SxC ExportResponses(
                string authToken, 
                int surveyId, 
                int pageNumber, 
                int resultsPerPage, 
                string filterField, 
                string filterValue, 
                string sortField, 
                bool sortAscending, 
                int period, 
                System.DateTime dtStart, 
                System.DateTime dtEnd, 
                bool DetailedResponseInfo, 
                bool DetailedUserInfo, 
                bool IncludeOpenEndedResults, 
                bool IncludeAliases, 
                bool IncludeHiddenItems, 
                bool IncludeIncompleteResponses, 
                bool StripHTMLTagsFromAnswers)
    {
        return base.Channel.ExportResponses(authToken, surveyId, pageNumber, resultsPerPage, filterField, filterValue, sortField, sortAscending, period, dtStart, dtEnd, DetailedResponseInfo, DetailedUserInfo, IncludeOpenEndedResults, IncludeAliases, IncludeHiddenItems, IncludeIncompleteResponses, StripHTMLTagsFromAnswers);
    }
    
    public Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfPagedListResultOfTabularResponseExportDataVUqw3SxCVUqw3SxC ExportResponsesTabular(
                string authToken, 
                int surveyId, 
                int pageNumber, 
                int resultsPerPage, 
                string filterField, 
                string filterValue, 
                string sortField, 
                bool sortAscending, 
                int period, 
                System.DateTime dtStart, 
                System.DateTime dtEnd, 
                bool DetailedResponseInfo, 
                bool DetailedUserInfo, 
                bool IncludeOpenEndedResults, 
                bool IncludeAliases, 
                bool IncludeHiddenItems, 
                bool IncludeIncompleteResponses, 
                bool StripHTMLTagsFromAnswers, 
                bool StripHTMLTagsFromQuestions, 
                bool MergeAnswersForSelectMany)
    {
        return base.Channel.ExportResponsesTabular(authToken, surveyId, pageNumber, resultsPerPage, filterField, filterValue, sortField, sortAscending, period, dtStart, dtEnd, DetailedResponseInfo, DetailedUserInfo, IncludeOpenEndedResults, IncludeAliases, IncludeHiddenItems, IncludeIncompleteResponses, StripHTMLTagsFromAnswers, StripHTMLTagsFromQuestions, MergeAnswersForSelectMany);
    }
}
