//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Checkbox.Wcf.Services.Proxies
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceOperationResultOfArrayOfPipeSourceVUqw3SxC", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    public partial class ServiceOperationResultOfArrayOfPipeSourceVUqw3SxC : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool CallSuccessField;
        
        private string FailureExceptionTypeField;
        
        private string FailureMessageField;
        
        private Checkbox.Wcf.Services.Proxies.PipeSource[] ResultDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CallSuccess
        {
            get
            {
                return this.CallSuccessField;
            }
            set
            {
                this.CallSuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailureExceptionType
        {
            get
            {
                return this.FailureExceptionTypeField;
            }
            set
            {
                this.FailureExceptionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailureMessage
        {
            get
            {
                return this.FailureMessageField;
            }
            set
            {
                this.FailureMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Checkbox.Wcf.Services.Proxies.PipeSource[] ResultData
        {
            get
            {
                return this.ResultDataField;
            }
            set
            {
                this.ResultDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PipeSource", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    public partial class PipeSource : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DisplayTextField;
        
        private string PipeTokenField;
        
        private string SourceTypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayText
        {
            get
            {
                return this.DisplayTextField;
            }
            set
            {
                this.DisplayTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PipeToken
        {
            get
            {
                return this.PipeTokenField;
            }
            set
            {
                this.PipeTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceType
        {
            get
            {
                return this.SourceTypeField;
            }
            set
            {
                this.SourceTypeField = value;
            }
        }
    }
    
   /* [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceOperationResultOfboolean", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    public partial class ServiceOperationResultOfboolean : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool CallSuccessField;
        
        private string FailureExceptionTypeField;
        
        private string FailureMessageField;
        
        private bool ResultDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CallSuccess
        {
            get
            {
                return this.CallSuccessField;
            }
            set
            {
                this.CallSuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailureExceptionType
        {
            get
            {
                return this.FailureExceptionTypeField;
            }
            set
            {
                this.FailureExceptionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailureMessage
        {
            get
            {
                return this.FailureMessageField;
            }
            set
            {
                this.FailureMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ResultData
        {
            get
            {
                return this.ResultDataField;
            }
            set
            {
                this.ResultDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceOperationResultOfstring", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    public partial class ServiceOperationResultOfstring : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool CallSuccessField;
        
        private string FailureExceptionTypeField;
        
        private string FailureMessageField;
        
        private string ResultDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CallSuccess
        {
            get
            {
                return this.CallSuccessField;
            }
            set
            {
                this.CallSuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailureExceptionType
        {
            get
            {
                return this.FailureExceptionTypeField;
            }
            set
            {
                this.FailureExceptionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailureMessage
        {
            get
            {
                return this.FailureMessageField;
            }
            set
            {
                this.FailureMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultData
        {
            get
            {
                return this.ResultDataField;
            }
            set
            {
                this.ResultDataField = value;
            }
        }
    }*/
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceOperationResultOfint", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    public partial class ServiceOperationResultOfint : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool CallSuccessField;
        
        private string FailureExceptionTypeField;
        
        private string FailureMessageField;
        
        private int ResultDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CallSuccess
        {
            get
            {
                return this.CallSuccessField;
            }
            set
            {
                this.CallSuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailureExceptionType
        {
            get
            {
                return this.FailureExceptionTypeField;
            }
            set
            {
                this.FailureExceptionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailureMessage
        {
            get
            {
                return this.FailureMessageField;
            }
            set
            {
                this.FailureMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResultData
        {
            get
            {
                return this.ResultDataField;
            }
            set
            {
                this.ResultDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceOperationResultOfArrayOfLocalizedTextValueVUqw3SxC", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    public partial class ServiceOperationResultOfArrayOfLocalizedTextValueVUqw3SxC : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool CallSuccessField;
        
        private string FailureExceptionTypeField;
        
        private string FailureMessageField;
        
        private Checkbox.Wcf.Services.Proxies.LocalizedTextValue[] ResultDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CallSuccess
        {
            get
            {
                return this.CallSuccessField;
            }
            set
            {
                this.CallSuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailureExceptionType
        {
            get
            {
                return this.FailureExceptionTypeField;
            }
            set
            {
                this.FailureExceptionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailureMessage
        {
            get
            {
                return this.FailureMessageField;
            }
            set
            {
                this.FailureMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Checkbox.Wcf.Services.Proxies.LocalizedTextValue[] ResultData
        {
            get
            {
                return this.ResultDataField;
            }
            set
            {
                this.ResultDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocalizedTextValue", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    public partial class LocalizedTextValue : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string LanguageCodeField;
        
        private string NameField;
        
        private string TextIdField;
        
        private string ValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LanguageCode
        {
            get
            {
                return this.LanguageCodeField;
            }
            set
            {
                this.LanguageCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TextId
        {
            get
            {
                return this.TextIdField;
            }
            set
            {
                this.TextIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    /*[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceOperationResultOfQuestionResultVUqw3SxC", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    public partial class ServiceOperationResultOfQuestionResultVUqw3SxC : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool CallSuccessField;
        
        private string FailureExceptionTypeField;
        
        private string FailureMessageField;
        
        private Checkbox.Wcf.Services.Proxies.QuestionResult ResultDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CallSuccess
        {
            get
            {
                return this.CallSuccessField;
            }
            set
            {
                this.CallSuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailureExceptionType
        {
            get
            {
                return this.FailureExceptionTypeField;
            }
            set
            {
                this.FailureExceptionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailureMessage
        {
            get
            {
                return this.FailureMessageField;
            }
            set
            {
                this.FailureMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Checkbox.Wcf.Services.Proxies.QuestionResult ResultData
        {
            get
            {
                return this.ResultDataField;
            }
            set
            {
                this.ResultDataField = value;
            }
        }
    }*/
    
    /*[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuestionResult", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    public partial class QuestionResult : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string MessageField;
        
        private bool YesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Yes
        {
            get
            {
                return this.YesField;
            }
            set
            {
                this.YesField = value;
            }
        }
    }*/
    /*
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceOperationResultOfanyType", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfArrayOfPipeSourceVUqw3SxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PipeSource[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PipeSource))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfboolean))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfstring))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfint))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfArrayOfLocalizedTextValueVUqw3SxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.LocalizedTextValue[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.LocalizedTextValue))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfQuestionResultVUqw3SxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.QuestionResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfSurveyItemMetaDataVUqw3SxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyItemMetaData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ItemMetaData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValueCollection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValue[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValue))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.TextData[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.TextData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyOptionMetaData[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyOptionMetaData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(int[]))]
    public partial class ServiceOperationResultOfanyType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool CallSuccessField;
        
        private string FailureExceptionTypeField;
        
        private string FailureMessageField;
        
        private object ResultDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CallSuccess
        {
            get
            {
                return this.CallSuccessField;
            }
            set
            {
                this.CallSuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailureExceptionType
        {
            get
            {
                return this.FailureExceptionTypeField;
            }
            set
            {
                this.FailureExceptionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailureMessage
        {
            get
            {
                return this.FailureMessageField;
            }
            set
            {
                this.FailureMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object ResultData
        {
            get
            {
                return this.ResultDataField;
            }
            set
            {
                this.ResultDataField = value;
            }
        }
    }*/
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceOperationResultOfSurveyItemMetaDataVUqw3SxC", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    public partial class ServiceOperationResultOfSurveyItemMetaDataVUqw3SxC : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool CallSuccessField;
        
        private string FailureExceptionTypeField;
        
        private string FailureMessageField;
        
        private Checkbox.Wcf.Services.Proxies.SurveyItemMetaData ResultDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CallSuccess
        {
            get
            {
                return this.CallSuccessField;
            }
            set
            {
                this.CallSuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailureExceptionType
        {
            get
            {
                return this.FailureExceptionTypeField;
            }
            set
            {
                this.FailureExceptionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailureMessage
        {
            get
            {
                return this.FailureMessageField;
            }
            set
            {
                this.FailureMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Checkbox.Wcf.Services.Proxies.SurveyItemMetaData ResultData
        {
            get
            {
                return this.ResultDataField;
            }
            set
            {
                this.ResultDataField = value;
            }
        }
    }
    /*
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SurveyItemMetaData", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    public partial class SurveyItemMetaData : Checkbox.Wcf.Services.Proxies.ItemMetaData
    {
        
        private int[] ChildItemIdsField;
        
        private int ColumnPositionField;
        
        private bool IsAnswerRequiredField;
        
        private bool IsAnswerableField;
        
        private Checkbox.Wcf.Services.Proxies.SurveyOptionMetaData[] OptionsField;
        
        private int RowPositionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] ChildItemIds
        {
            get
            {
                return this.ChildItemIdsField;
            }
            set
            {
                this.ChildItemIdsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ColumnPosition
        {
            get
            {
                return this.ColumnPositionField;
            }
            set
            {
                this.ColumnPositionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAnswerRequired
        {
            get
            {
                return this.IsAnswerRequiredField;
            }
            set
            {
                this.IsAnswerRequiredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAnswerable
        {
            get
            {
                return this.IsAnswerableField;
            }
            set
            {
                this.IsAnswerableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Checkbox.Wcf.Services.Proxies.SurveyOptionMetaData[] Options
        {
            get
            {
                return this.OptionsField;
            }
            set
            {
                this.OptionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowPosition
        {
            get
            {
                return this.RowPositionField;
            }
            set
            {
                this.RowPositionField = value;
            }
        }
    }*/
    /*
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemMetaData", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyItemMetaData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfArrayOfPipeSourceVUqw3SxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PipeSource[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.PipeSource))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfboolean))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfstring))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfint))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfArrayOfLocalizedTextValueVUqw3SxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.LocalizedTextValue[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.LocalizedTextValue))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfQuestionResultVUqw3SxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.QuestionResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfanyType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfSurveyItemMetaDataVUqw3SxC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValueCollection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValue[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SimpleNameValue))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.TextData[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.TextData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyOptionMetaData[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Checkbox.Wcf.Services.Proxies.SurveyOptionMetaData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(int[]))]
    public partial class ItemMetaData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private object AdditionalDataField;
        
        private int ItemIdField;
        
        private int ItemPositionField;
        
        private int PagePositionField;
        
        private Checkbox.Wcf.Services.Proxies.SimpleNameValueCollection PropertiesField;
        
        private Checkbox.Wcf.Services.Proxies.TextData[] TextDataField;
        
        private string TypeNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object AdditionalData
        {
            get
            {
                return this.AdditionalDataField;
            }
            set
            {
                this.AdditionalDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemId
        {
            get
            {
                return this.ItemIdField;
            }
            set
            {
                this.ItemIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemPosition
        {
            get
            {
                return this.ItemPositionField;
            }
            set
            {
                this.ItemPositionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PagePosition
        {
            get
            {
                return this.PagePositionField;
            }
            set
            {
                this.PagePositionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Checkbox.Wcf.Services.Proxies.SimpleNameValueCollection Properties
        {
            get
            {
                return this.PropertiesField;
            }
            set
            {
                this.PropertiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Checkbox.Wcf.Services.Proxies.TextData[] TextData
        {
            get
            {
                return this.TextDataField;
            }
            set
            {
                this.TextDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeName
        {
            get
            {
                return this.TypeNameField;
            }
            set
            {
                this.TypeNameField = value;
            }
        }
    }*/
    /*
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SimpleNameValueCollection", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    public partial class SimpleNameValueCollection : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Checkbox.Wcf.Services.Proxies.SimpleNameValue[] NameValueListField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Checkbox.Wcf.Services.Proxies.SimpleNameValue[] NameValueList
        {
            get
            {
                return this.NameValueListField;
            }
            set
            {
                this.NameValueListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SimpleNameValue", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    public partial class SimpleNameValue : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string NameField;
        
        private string ValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }*/
    /*
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TextData", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    public partial class TextData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string LanguageCodeField;
        
        private Checkbox.Wcf.Services.Proxies.SimpleNameValueCollection TextValuesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LanguageCode
        {
            get
            {
                return this.LanguageCodeField;
            }
            set
            {
                this.LanguageCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Checkbox.Wcf.Services.Proxies.SimpleNameValueCollection TextValues
        {
            get
            {
                return this.TextValuesField;
            }
            set
            {
                this.TextValuesField = value;
            }
        }
    }*/
    /*
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SurveyOptionMetaData", Namespace="http://schemas.datacontract.org/2004/07/Checkbox.Wcf.Services.Proxies")]
    public partial class SurveyOptionMetaData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AliasField;
        
        private int IdField;
        
        private bool IsDefaultField;
        
        private bool IsOtherField;
        
        private double PointsField;
        
        private int PositionField;
        
        private Checkbox.Wcf.Services.Proxies.TextData[] TextDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Alias
        {
            get
            {
                return this.AliasField;
            }
            set
            {
                this.AliasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDefault
        {
            get
            {
                return this.IsDefaultField;
            }
            set
            {
                this.IsDefaultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOther
        {
            get
            {
                return this.IsOtherField;
            }
            set
            {
                this.IsOtherField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Points
        {
            get
            {
                return this.PointsField;
            }
            set
            {
                this.PointsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Position
        {
            get
            {
                return this.PositionField;
            }
            set
            {
                this.PositionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Checkbox.Wcf.Services.Proxies.TextData[] TextData
        {
            get
            {
                return this.TextDataField;
            }
            set
            {
                this.TextDataField = value;
            }
        }
    }*/
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ISurveyEditorService")]
public interface ISurveyEditorService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyEditorService/ListPipeSources", ReplyAction="http://tempuri.org/ISurveyEditorService/ListPipeSourcesResponse")]
    Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfArrayOfPipeSourceVUqw3SxC ListPipeSources(string authToken, int surveyId, int maxPagePosition, string languageCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyEditorService/ToggleSetting", ReplyAction="http://tempuri.org/ISurveyEditorService/ToggleSettingResponse")]
    Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfboolean ToggleSetting(string authToken, int surveyId, string settingName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyEditorService/UpdateSetting", ReplyAction="http://tempuri.org/ISurveyEditorService/UpdateSettingResponse")]
    Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfstring UpdateSetting(string authToken, int surveyId, string settingName, string settingValueAsString);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyEditorService/SetAlternateUrl", ReplyAction="http://tempuri.org/ISurveyEditorService/SetAlternateUrlResponse")]
    Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfstring SetAlternateUrl(string authToken, int surveyId, string altUrl);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyEditorService/SetStyleTemplate", ReplyAction="http://tempuri.org/ISurveyEditorService/SetStyleTemplateResponse")]
    Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfint SetStyleTemplate(string authToken, int surveyId, int styleTemplateId, string styleType);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyEditorService/GetLocalizableTexts", ReplyAction="http://tempuri.org/ISurveyEditorService/GetLocalizableTextsResponse")]
    Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfArrayOfLocalizedTextValueVUqw3SxC GetLocalizableTexts(string authToken, int surveyId, string languageCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyEditorService/WillRulesBeChangedIfPageDeletes", ReplyAction="http://tempuri.org/ISurveyEditorService/WillRulesBeChangedIfPageDeletesResponse")]
    Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfQuestionResultVUqw3SxC WillRulesBeChangedIfPageDeletes(string authToken, int surveyId, int pageId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyEditorService/UpdateSurveyText", ReplyAction="http://tempuri.org/ISurveyEditorService/UpdateSurveyTextResponse")]
    Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfanyType UpdateSurveyText(string authToken, int surveyId, string textKey, string textValue, string languageCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyEditorService/SetDefaultLanguage", ReplyAction="http://tempuri.org/ISurveyEditorService/SetDefaultLanguageResponse")]
    Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfboolean SetDefaultLanguage(string authToken, int surveyId, string language);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyEditorService/AddDefaultLanguage", ReplyAction="http://tempuri.org/ISurveyEditorService/AddDefaultLanguageResponse")]
    Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfboolean AddDefaultLanguage(string authToken, int surveyId, string language);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyEditorService/RemoveDefaultLanguage", ReplyAction="http://tempuri.org/ISurveyEditorService/RemoveDefaultLanguageResponse")]
    Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfboolean RemoveDefaultLanguage(string authToken, int surveyId, string language);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyEditorService/GetDateFormat", ReplyAction="http://tempuri.org/ISurveyEditorService/GetDateFormatResponse")]
    Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfstring GetDateFormat(string authToken);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyEditorService/GetTimeFormat", ReplyAction="http://tempuri.org/ISurveyEditorService/GetTimeFormatResponse")]
    Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfstring GetTimeFormat(string authToken);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyEditorService/GetItemMetadata", ReplyAction="http://tempuri.org/ISurveyEditorService/GetItemMetadataResponse")]
    Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfSurveyItemMetaDataVUqw3SxC GetItemMetadata(int itemId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyEditorService/UpdateItemMetadata", ReplyAction="http://tempuri.org/ISurveyEditorService/UpdateItemMetadataResponse")]
    Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfboolean UpdateItemMetadata(int itemId, Checkbox.Wcf.Services.Proxies.ItemMetaData itemMetaData);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyEditorService/ToggleItemActiveStatus", ReplyAction="http://tempuri.org/ISurveyEditorService/ToggleItemActiveStatusResponse")]
    Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfanyType ToggleItemActiveStatus(string authToken, int surveyId, int itemId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyEditorService/GetItemIsActive", ReplyAction="http://tempuri.org/ISurveyEditorService/GetItemIsActiveResponse")]
    Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfboolean GetItemIsActive(string authToken, int surveyId, int itemId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyEditorService/GetStatus", ReplyAction="http://tempuri.org/ISurveyEditorService/GetStatusResponse")]
    Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfstring GetStatus(string authToken, int surveyId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyEditorService/UpdateConditionSource", ReplyAction="http://tempuri.org/ISurveyEditorService/UpdateConditionSourceResponse")]
    Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfanyType UpdateConditionSource(string authToken, int surveyId, string value);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ISurveyEditorServiceChannel : ISurveyEditorService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class SurveyEditorServiceClient : System.ServiceModel.ClientBase<ISurveyEditorService>, ISurveyEditorService
{
    
    public SurveyEditorServiceClient()
    {
    }
    
    public SurveyEditorServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public SurveyEditorServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SurveyEditorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SurveyEditorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfArrayOfPipeSourceVUqw3SxC ListPipeSources(string authToken, int surveyId, int maxPagePosition, string languageCode)
    {
        return base.Channel.ListPipeSources(authToken, surveyId, maxPagePosition, languageCode);
    }
    
    public Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfboolean ToggleSetting(string authToken, int surveyId, string settingName)
    {
        return base.Channel.ToggleSetting(authToken, surveyId, settingName);
    }
    
    public Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfstring UpdateSetting(string authToken, int surveyId, string settingName, string settingValueAsString)
    {
        return base.Channel.UpdateSetting(authToken, surveyId, settingName, settingValueAsString);
    }
    
    public Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfstring SetAlternateUrl(string authToken, int surveyId, string altUrl)
    {
        return base.Channel.SetAlternateUrl(authToken, surveyId, altUrl);
    }
    
    public Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfint SetStyleTemplate(string authToken, int surveyId, int styleTemplateId, string styleType)
    {
        return base.Channel.SetStyleTemplate(authToken, surveyId, styleTemplateId, styleType);
    }
    
    public Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfArrayOfLocalizedTextValueVUqw3SxC GetLocalizableTexts(string authToken, int surveyId, string languageCode)
    {
        return base.Channel.GetLocalizableTexts(authToken, surveyId, languageCode);
    }
    
    public Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfQuestionResultVUqw3SxC WillRulesBeChangedIfPageDeletes(string authToken, int surveyId, int pageId)
    {
        return base.Channel.WillRulesBeChangedIfPageDeletes(authToken, surveyId, pageId);
    }
    
    public Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfanyType UpdateSurveyText(string authToken, int surveyId, string textKey, string textValue, string languageCode)
    {
        return base.Channel.UpdateSurveyText(authToken, surveyId, textKey, textValue, languageCode);
    }
    
    public Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfboolean SetDefaultLanguage(string authToken, int surveyId, string language)
    {
        return base.Channel.SetDefaultLanguage(authToken, surveyId, language);
    }
    
    public Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfboolean AddDefaultLanguage(string authToken, int surveyId, string language)
    {
        return base.Channel.AddDefaultLanguage(authToken, surveyId, language);
    }
    
    public Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfboolean RemoveDefaultLanguage(string authToken, int surveyId, string language)
    {
        return base.Channel.RemoveDefaultLanguage(authToken, surveyId, language);
    }
    
    public Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfstring GetDateFormat(string authToken)
    {
        return base.Channel.GetDateFormat(authToken);
    }
    
    public Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfstring GetTimeFormat(string authToken)
    {
        return base.Channel.GetTimeFormat(authToken);
    }
    
    public Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfSurveyItemMetaDataVUqw3SxC GetItemMetadata(int itemId)
    {
        return base.Channel.GetItemMetadata(itemId);
    }
    
    public Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfboolean UpdateItemMetadata(int itemId, Checkbox.Wcf.Services.Proxies.ItemMetaData itemMetaData)
    {
        return base.Channel.UpdateItemMetadata(itemId, itemMetaData);
    }
    
    public Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfanyType ToggleItemActiveStatus(string authToken, int surveyId, int itemId)
    {
        return base.Channel.ToggleItemActiveStatus(authToken, surveyId, itemId);
    }
    
    public Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfboolean GetItemIsActive(string authToken, int surveyId, int itemId)
    {
        return base.Channel.GetItemIsActive(authToken, surveyId, itemId);
    }
    
    public Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfstring GetStatus(string authToken, int surveyId)
    {
        return base.Channel.GetStatus(authToken, surveyId);
    }
    
    public Checkbox.Wcf.Services.Proxies.ServiceOperationResultOfanyType UpdateConditionSource(string authToken, int surveyId, string value)
    {
        return base.Channel.UpdateConditionSource(authToken, surveyId, value);
    }
}
